/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "knxxnukmvfbjjfzydaqe"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtueHhudWttdmZiampmenlkYXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjI1MTEsImV4cCI6MjA5MDAzODUxMX0.x1OLCgUKkWx1gEQUtbf-OshVz_Nd-Wz3-3uV1MxShL8"